### ISSUE TITLE
Readme improvements

### ISSUE THREAD

**Issue by arturmuller** [saamo/api-doc-test#1]
There are a few minor things that I think would improve the readme:
- Use a real-world-looking data in the structure example (and the accompanying generated blueprint file)
- Introduce the _header file earlier in the readme — it is not obvious why you need it until the end of the readme, but the examples already have it.
- "One test file" => "Single test file"
- "More test files" => "Multiple test files"

**Comment by saamo** [comment]
I agree with all of your points above 👍🏿

**Comment by saamo** [comment]
I agree with all of your points above 👍🏿
