### ISSUE TITLE
Make the use of this package more user friendly

### ISSUE THREAD

**Issue by arturmuller** [saamo/api-doc-test#2]
As I was reading though the examples I have noticed that it is kinda awkward that I always have to hunt down where the apiDocTest function is called. There is a lot of reliance on the user doing things before they can plug them into the function, when I think most of these could be handled by the package itself. (Maybe I am missing something?)

The promise of this package is to generate an API Blueprint, so that is the 'edge' of this package in my eyes and you don't have to be modular beyond that I think. After all, if the user needs something more specific, they can always use Acquit or something like that directly — this should be pretty plug'n'play imo.

Anyways, so what if the api was something more along the lines of:

```javascript
var generateDocs = require('api-doc-test');

var header = {
  title: 'Lobster Chat API',
  description: 'This API provides access to the Lobster Chat messaging service.',
  metadata: {
    format: '1A',
    host: 'http://api.lobsterchat.com/'
  }
}

generateDocs(header, './**/*.test.js');

```

I guess you should also somehow deal with where the output goes and how the generated file is called but I think the above is hopefully enough to get my point across.

What do you think?

**Comment by saamo** [comment]
This is definitely a good approach. I was trying to follow _the single responsibility principle_ (just generate blueprint from test) but at this moment it's clear that the use case (and responsibility) is more about “generating _final_ API Blueprint from all tests”, not just generating it from one test. Hm, quite obvious. Thanks for pointing this out!

**Comment by arturmuller** [comment]
Easy to critique, hard to build. ;)
